# Generated by Django 4.2.20 on 2026-02-14 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('original_file', models.FileField(max_length=500, upload_to=videos.models.video_upload_path)),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Progress percentage')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('full_text', models.TextField()),
                ('json_data', models.JSONField(help_text='Detailed transcript with timestamps')),
                ('word_timestamps', models.JSONField(blank=True, help_text='Word-level timestamps', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='videos.video')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=videos.models.short_video_path)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('style', models.CharField(default='default', help_text='Style template used', max_length=100)),
                ('include_music', models.BooleanField(default=False)),
                ('music_track', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_style', models.CharField(default='default', max_length=100)),
                ('font_size', models.IntegerField(default=24)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_videos', to='videos.video')),
            ],
            options={
                'db_table': 'short_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('transcription', 'Transcription'), ('summarization', 'Summarization'), ('highlight_detection', 'Highlight Detection'), ('short_generation', 'Short Video Generation'), ('thumbnail_generation', 'Thumbnail Generation')], max_length=50)),
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='videos.video')),
            ],
            options={
                'db_table': 'processing_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('importance_score', models.FloatField(default=0.0, help_text='AI-calculated importance score')),
                ('reason', models.CharField(blank=True, help_text='Why this segment was selected', max_length=255)),
                ('transcript_snippet', models.TextField(blank=True, help_text='Transcript text in this segment')),
                ('used_in_short', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_segments', to='videos.video')),
            ],
            options={
                'db_table': 'highlight_segments',
                'ordering': ['-importance_score'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('full', 'Full Summary'), ('bullet', 'Bullet Points'), ('short', 'Short Script (30-60 sec)'), ('timestamps', 'Timestamp Summary')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('key_topics', models.JSONField(blank=True, help_text='List of key topics', null=True)),
                ('model_used', models.CharField(default='facebook/bart-large-cnn', max_length=100)),
                ('generation_time', models.FloatField(default=0.0, help_text='Time taken to generate in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='videos.video')),
            ],
            options={
                'db_table': 'summaries',
                'unique_together': {('video', 'summary_type')},
            },
        ),
    ]
