# Generated by Django 4.2.20 on 2026-02-21 13:30

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL for videos imported from YouTube', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=videos.models.video_upload_path),
        ),
    ]
