# Generated by Django 4.2.20 on 2026-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_hybrid_asr_prompt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting_audio', 'Extracting Audio'), ('transcribing', 'Transcribing'), ('cleaning_transcript', 'Cleaning Transcript'), ('transcript_ready', 'Transcript Ready'), ('summarizing_quick', 'Summarizing Quick'), ('summarizing_final', 'Summarizing Final'), ('summarizing', 'Summarizing'), ('indexing_chat', 'Indexing Chat'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
